CREATE SCHEMA IF NOT EXISTS app;
CREATE TABLE IF NOT EXISTS app.users (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,username varchar(32) NOT NULL UNIQUE,display_name varchar(64) NOT NULL DEFAULT '',password_hash text NOT NULL,role varchar(32) NOT NULL DEFAULT 'user',enabled boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS app.user_sessions (token_hash bytea PRIMARY KEY,user_id bigint NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE app.user_sessions ADD COLUMN IF NOT EXISTS last_seen_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE app.user_sessions ADD COLUMN IF NOT EXISTS cookie_session boolean NOT NULL DEFAULT false;
DELETE FROM app.user_sessions WHERE cookie_session = false;
CREATE INDEX IF NOT EXISTS user_sessions_user_id_idx ON app.user_sessions(user_id);
CREATE INDEX IF NOT EXISTS user_sessions_expires_at_idx ON app.user_sessions(expires_at);
CREATE TABLE app.preauth_sessions (token_hash bytea PRIMARY KEY,expires_at timestamptz NOT NULL);
CREATE TABLE app.setup_tokens (token_hash bytea PRIMARY KEY,expires_at timestamptz NOT NULL);
CREATE TABLE app.runtime_installations (id text PRIMARY KEY,kind text NOT NULL CHECK(kind IN ('node','go')),path text NOT NULL UNIQUE,revision bigint NOT NULL DEFAULT 1,payload jsonb NOT NULL);
CREATE TABLE app.runtime_defaults (kind text PRIMARY KEY CHECK(kind IN ('node','go')),installation_id text NOT NULL REFERENCES app.runtime_installations(id));
CREATE TABLE app.runtime_catalog (id text PRIMARY KEY,kind text NOT NULL,checked_at timestamptz NOT NULL,payload jsonb NOT NULL);
CREATE TABLE app.catalog_status (kind text PRIMARY KEY,checked_at timestamptz,error_code text);
CREATE TABLE app.managed_apps (id text PRIMARY KEY,name text NOT NULL UNIQUE,runtime_id text REFERENCES app.runtime_installations(id),revision bigint NOT NULL DEFAULT 1,payload jsonb NOT NULL);
CREATE TABLE app.app_secrets (app_id text NOT NULL REFERENCES app.managed_apps(id) ON DELETE CASCADE,name text NOT NULL,secret boolean NOT NULL,ciphertext bytea NOT NULL,PRIMARY KEY(app_id,name));
CREATE TABLE app.operation_plans (id text PRIMARY KEY,actor_id bigint NOT NULL REFERENCES app.users(id),expires_at timestamptz NOT NULL,payload jsonb NOT NULL,encrypted_input bytea,consumed boolean NOT NULL DEFAULT false);
CREATE TABLE app.tasks (id text PRIMARY KEY,actor_id bigint NOT NULL REFERENCES app.users(id),plan_id text UNIQUE REFERENCES app.operation_plans(id),status text NOT NULL CHECK(status IN ('queued','running','succeeded','failed','canceled','interrupted')),revision bigint NOT NULL DEFAULT 1,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX tasks_queue_idx ON app.tasks(status,created_at);
CREATE TABLE app.task_inputs (task_id text PRIMARY KEY REFERENCES app.tasks(id) ON DELETE CASCADE,ciphertext bytea NOT NULL);
CREATE TABLE app.task_logs (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,task_id text NOT NULL REFERENCES app.tasks(id) ON DELETE CASCADE,at timestamptz NOT NULL DEFAULT now(),level text NOT NULL,message text NOT NULL);
CREATE TABLE app.idempotency_records (actor_id bigint NOT NULL REFERENCES app.users(id),key text NOT NULL,fingerprint text NOT NULL,task_id text NOT NULL REFERENCES app.tasks(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(actor_id,key));
CREATE TABLE app.event_outbox (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,resource_id text NOT NULL,revision bigint NOT NULL,event_name text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),published_at timestamptz,UNIQUE(resource_id,revision,event_name));
ALTER TABLE app.event_outbox ADD COLUMN actor_id bigint;
CREATE TABLE app.metrics_aggregates (metric text NOT NULL,device_id text NOT NULL DEFAULT '',at timestamptz NOT NULL,avg double precision,min double precision,max double precision,sample_count int NOT NULL,PRIMARY KEY(metric,device_id,at));
CREATE INDEX metrics_time_idx ON app.metrics_aggregates(at);
CREATE TABLE app.settings (id boolean PRIMARY KEY DEFAULT true CHECK(id),revision bigint NOT NULL DEFAULT 1,payload jsonb NOT NULL);
INSERT INTO app.settings(id,payload) VALUES(true,'{"displayTimezone":"server","metricsRetentionHours":24,"taskRetentionDays":30,"auditRetentionDays":30}') ON CONFLICT DO NOTHING;
CREATE TABLE app.audit_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,actor_id bigint REFERENCES app.users(id),at timestamptz NOT NULL DEFAULT now(),action text NOT NULL,resource_id text,task_id text,request_id text NOT NULL DEFAULT '',result text NOT NULL,message text NOT NULL);
CREATE INDEX audit_time_idx ON app.audit_events(at);
CREATE TABLE app.log_exports(id text PRIMARY KEY,actor_id bigint NOT NULL REFERENCES app.users(id),path text NOT NULL,expires_at timestamptz NOT NULL,bytes bigint NOT NULL CHECK(bytes<=52428800));

CREATE TABLE app.panel_logs(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,at timestamptz NOT NULL DEFAULT now(),level text NOT NULL,message text NOT NULL);
