import type { ShadcnTokenSet, ThemeMode } from "@/types/theme.type";
import type { ThemeConfig } from "antd";
import { theme as antdTheme } from "antd";

/**
 * shadcnTokens 集中定义亮色和暗色模式的基础设计令牌。
 * Ant Design 组件主题和全局样式均从该映射派生。
 */
export const shadcnTokens: Record<ThemeMode, ShadcnTokenSet> = {
  light: {
    background: "#FFFFFF",
    foreground: "#0A0A0A",
    card: "#FFFFFF",
    cardForeground: "#0A0A0A",
    popover: "#FFFFFF",
    popoverForeground: "#252525",
    primary: "#171717",
    primaryForeground: "#FAFAFA",
    secondary: "#F5F5F5",
    secondaryForeground: "#171717",
    muted: "#F7F7F7",
    mutedForeground: "#737373",
    accent: "#F5F5F5",
    accentForeground: "#171717",
    destructive: "#E7000B",
    border: "#E5E5E5",
    input: "#E5E5E5",
    ring: "#A1A1A1",
    radius: 10,
    success: "#009689",
    warning: "#FE9A00",
  },
  dark: {
    background: "#0A0A0A",
    foreground: "#FAFAFA",
    card: "#171717",
    cardForeground: "#FAFAFA",
    popover: "#171717",
    popoverForeground: "#FAFAFA",
    primary: "#E5E5E5",
    primaryForeground: "#171717",
    secondary: "#262626",
    secondaryForeground: "#FAFAFA",
    muted: "#262626",
    mutedForeground: "#A1A1A1",
    accent: "#262626",
    accentForeground: "#FAFAFA",
    destructive: "#FF6467",
    border: "#FFFFFF1A",
    input: "#FFFFFF26",
    ring: "#737373",
    radius: 10,
    success: "#00BC7D",
    warning: "#FE9A00",
  },
};

/**
 * alpha 为十六进制或 rgb 颜色添加指定透明度。
 * 无法识别的颜色格式保持原值，避免破坏合法 CSS 颜色。
 */
function alpha(color: string, opacity: number) {
  if (color.startsWith("#") && color.length === 7) {
    const red = Number.parseInt(color.slice(1, 3), 16);
    const green = Number.parseInt(color.slice(3, 5), 16);
    const blue = Number.parseInt(color.slice(5, 7), 16);

    return `rgba(${red}, ${green}, ${blue}, ${opacity})`;
  }

  if (color.startsWith("rgb(")) {
    return color.replace("rgb(", "rgba(").replace(")", `, ${opacity})`);
  }

  return color;
}

/**
 * createAntdTheme 根据当前模式生成完整的 Ant Design 主题配置。
 * 主题令牌统一继承 shadcnTokens，确保组件视觉与全局风格一致。
 */
export function createAntdTheme(mode: ThemeMode): ThemeConfig {
  const tokens = shadcnTokens[mode];
  const isDark = mode === "dark";
  const baseBg = tokens.background;
  const cardBg = tokens.card;
  const elevatedBg = tokens.popover;
  const textSecondary = alpha(tokens.foreground, isDark ? 0.72 : 0.68);
  const textQuaternary = alpha(tokens.mutedForeground, 0.45);
  const focusShadow = `0 0 0 2px ${alpha(tokens.ring, isDark ? 0.32 : 0.22)}`;
  const errorShadow = `0 0 0 2px ${alpha(tokens.destructive, isDark ? 0.32 : 0.18)}`;
  const warningShadow = `0 0 0 2px ${alpha(tokens.warning, isDark ? 0.32 : 0.18)}`;
  const hoverBg = tokens.accent;
  const selectedBg = alpha(tokens.primary, isDark ? 0.22 : 0.1);
  const selectedHoverBg = alpha(tokens.primary, isDark ? 0.28 : 0.14);
  const disabledBg = tokens.muted;
  const disabledText = alpha(tokens.foreground, isDark ? 0.32 : 0.34);
  const infoBg = alpha(tokens.ring, isDark ? 0.18 : 0.1);
  const successBg = alpha(tokens.success, isDark ? 0.18 : 0.1);
  const warningBg = alpha(tokens.warning, isDark ? 0.18 : 0.12);
  const errorBg = alpha(tokens.destructive, isDark ? 0.2 : 0.1);
  const popupZIndex = 1050;

  return {
    algorithm: isDark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
    cssVar: {
      key: `zx-panel-${mode}`,
      prefix: "ant",
    },
    hashed: true,
    token: {
      borderRadius: tokens.radius,
      colorBgBase: baseBg,
      colorBgContainer: baseBg,
      colorBgElevated: elevatedBg,
      colorBgLayout: baseBg,
      colorBorder: tokens.border,
      colorBorderSecondary: tokens.input,
      colorError: tokens.destructive,
      colorInfo: tokens.ring,
      colorLink: tokens.primary,
      colorPrimary: tokens.primary,
      colorSuccess: tokens.success,
      colorText: tokens.foreground,
      colorTextBase: tokens.foreground,
      colorTextDisabled: disabledText,
      colorTextQuaternary: textQuaternary,
      colorTextSecondary: textSecondary,
      colorTextTertiary: tokens.mutedForeground,
      colorWarning: tokens.warning,
      controlHeightLG: 40,
      controlHeightSM: 32,
      controlHeight: 36,
      controlOutline: alpha(tokens.ring, isDark ? 0.32 : 0.22),
      controlOutlineWidth: 2,
      fontFamily:
        "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
      fontFamilyCode:
        "\"Cascadia Code\", \"SFMono-Regular\", Consolas, \"Liberation Mono\", monospace",
      fontSize: 14,
      lineType: "solid",
      lineWidth: 1,
      wireframe: false,
    },
    components: {
      Alert: {
        colorErrorBg: errorBg,
        colorErrorBorder: alpha(tokens.destructive, isDark ? 0.42 : 0.26),
        colorInfoBg: infoBg,
        colorInfoBorder: alpha(tokens.ring, isDark ? 0.36 : 0.24),
        colorSuccessBg: successBg,
        colorSuccessBorder: alpha(tokens.success, isDark ? 0.42 : 0.26),
        colorWarningBg: warningBg,
        colorWarningBorder: alpha(tokens.warning, isDark ? 0.44 : 0.3),
        defaultPadding: "10px 14px",
        withDescriptionIconSize: 20,
        withDescriptionPadding: "14px 16px",
      },
      Breadcrumb: {
        itemColor: tokens.mutedForeground,
        lastItemColor: tokens.foreground,
        linkColor: tokens.mutedForeground,
        linkHoverColor: tokens.foreground,
        separatorColor: textQuaternary,
        separatorMargin: 8,
      },
      Button: {
        dangerColor: tokens.destructive,
        dangerShadow: "none",
        defaultActiveBg: hoverBg,
        defaultActiveBorderColor: tokens.ring,
        defaultActiveColor: tokens.accentForeground,
        defaultBg: baseBg,
        defaultBgDisabled: disabledBg,
        defaultBorderColor: tokens.input,
        defaultColor: tokens.foreground,
        defaultGhostBorderColor: tokens.border,
        defaultGhostColor: tokens.foreground,
        defaultHoverBg: hoverBg,
        defaultHoverBorderColor: tokens.ring,
        defaultHoverColor: tokens.accentForeground,
        defaultShadow: "none",
        fontWeight: 500,
        ghostBg: "transparent",
        linkHoverBg: "transparent",
        paddingInline: 14,
        paddingInlineLG: 18,
        paddingInlineSM: 10,
        primaryColor: tokens.primaryForeground,
        primaryShadow: "none",
        solidTextColor: tokens.primaryForeground,
        textHoverBg: hoverBg,
        textTextActiveColor: tokens.foreground,
        textTextColor: tokens.foreground,
        textTextHoverColor: tokens.foreground,
      },
      Card: {
        actionsBg: cardBg,
        actionsLiMargin: "10px 0",
        bodyPadding: 20,
        bodyPaddingSM: 14,
        colorBgContainer: cardBg,
        extraColor: tokens.mutedForeground,
        headerBg: cardBg,
        headerFontSize: 15,
        headerFontSizeSM: 14,
        headerHeight: 48,
        headerHeightSM: 40,
        headerPadding: 20,
        headerPaddingSM: 14,
        tabsMarginBottom: -16,
      },
      Cascader: {
        controlItemWidth: 128,
        controlWidth: 184,
        dropdownHeight: 180,
        menuPadding: 4,
        optionPadding: "6px 12px",
        optionSelectedBg: selectedBg,
        optionSelectedColor: tokens.foreground,
        optionSelectedFontWeight: 500,
      },
      Collapse: {
        borderlessContentBg: baseBg,
        borderlessContentPadding: "10px 0 16px",
        contentBg: baseBg,
        contentPadding: "12px 16px 16px",
        contentPaddingLG: "16px 20px 20px",
        contentPaddingSM: "8px 12px 12px",
        headerBg: tokens.muted,
        headerPadding: "12px 16px",
        headerPaddingLG: "16px 20px",
        headerPaddingSM: "8px 12px",
      },
      DatePicker: {
        activeBg: baseBg,
        activeBorderColor: tokens.ring,
        activeShadow: focusShadow,
        addonBg: tokens.muted,
        cellActiveWithRangeBg: selectedBg,
        cellBgDisabled: disabledBg,
        cellHoverBg: hoverBg,
        cellHoverWithRangeBg: selectedHoverBg,
        cellRangeBorderColor: tokens.ring,
        colorBgElevated: elevatedBg,
        errorActiveShadow: errorShadow,
        hoverBg: baseBg,
        hoverBorderColor: tokens.ring,
        multipleItemBg: tokens.secondary,
        multipleItemBorderColor: tokens.border,
        multipleSelectorBgDisabled: disabledBg,
        paddingBlock: 6,
        paddingBlockLG: 7,
        paddingBlockSM: 4,
        paddingInline: 11,
        paddingInlineLG: 12,
        paddingInlineSM: 8,
        warningActiveShadow: warningShadow,
        zIndexPopup: popupZIndex,
      },
      Descriptions: {
        contentColor: tokens.foreground,
        extraColor: tokens.mutedForeground,
        itemPaddingBottom: 12,
        itemPaddingEnd: 16,
        labelBg: tokens.muted,
        labelColor: tokens.mutedForeground,
        titleColor: tokens.foreground,
        titleMarginBottom: 16,
      },
      Drawer: {
        footerPaddingBlock: 12,
        footerPaddingInline: 16,
        zIndexPopup: 1000,
      },
      Dropdown: {
        colorBgElevated: elevatedBg,
        controlItemBgActive: selectedBg,
        controlItemBgHover: hoverBg,
        zIndexPopup: popupZIndex,
      },
      Empty: {
        colorText: tokens.mutedForeground,
      },
      Form: {
        inlineItemMarginBottom: 0,
        itemMarginBottom: 18,
        labelColor: tokens.foreground,
        labelColonMarginInlineEnd: 8,
        labelColonMarginInlineStart: 2,
        labelFontSize: 14,
        labelHeight: 32,
        labelRequiredMarkColor: tokens.destructive,
        verticalLabelMargin: "0 0 6px",
        verticalLabelPadding: 0,
      },
      Input: {
        activeBg: baseBg,
        activeBorderColor: tokens.ring,
        activeShadow: focusShadow,
        addonBg: tokens.muted,
        errorActiveShadow: errorShadow,
        hoverBg: baseBg,
        hoverBorderColor: tokens.ring,
        inputFontSize: 14,
        inputFontSizeLG: 14,
        inputFontSizeSM: 13,
        paddingBlock: 6,
        paddingBlockLG: 7,
        paddingBlockSM: 4,
        paddingInline: 11,
        paddingInlineLG: 12,
        paddingInlineSM: 8,
        warningActiveShadow: warningShadow,
      },
      InputNumber: {
        activeBg: baseBg,
        activeBorderColor: tokens.ring,
        activeShadow: focusShadow,
        addonBg: tokens.muted,
        controlWidth: 96,
        errorActiveShadow: errorShadow,
        filledHandleBg: tokens.muted,
        handleActiveBg: hoverBg,
        handleBg: baseBg,
        handleBorderColor: tokens.border,
        handleHoverColor: tokens.foreground,
        hoverBg: baseBg,
        hoverBorderColor: tokens.ring,
        paddingBlock: 6,
        paddingBlockLG: 7,
        paddingBlockSM: 4,
        paddingInline: 11,
        paddingInlineLG: 12,
        paddingInlineSM: 8,
        warningActiveShadow: warningShadow,
      },
      Layout: {
        bodyBg: baseBg,
        colorBgBody: baseBg,
        colorBgHeader: baseBg,
        colorBgLayout: baseBg,
        footerBg: baseBg,
        footerPadding: "16px 24px",
        headerBg: baseBg,
        headerColor: tokens.foreground,
        headerHeight: 56,
        headerPadding: "0 24px",
        lightSiderBg: baseBg,
        lightTriggerBg: tokens.muted,
        lightTriggerColor: tokens.foreground,
        siderBg: baseBg,
        triggerBg: tokens.muted,
        triggerColor: tokens.foreground,
      },
      List: {
        avatarMarginRight: 12,
        descriptionFontSize: 13,
        emptyTextPadding: "24px 0",
        footerBg: baseBg,
        headerBg: baseBg,
        itemPadding: "12px 0",
        itemPaddingLG: "16px 0",
        itemPaddingSM: "8px 0",
        metaMarginBottom: 12,
        titleMarginBottom: 6,
      },
      Menu: {
        activeBarBorderWidth: 0,
        activeBarHeight: 2,
        darkDangerItemActiveBg: errorBg,
        darkDangerItemColor: tokens.destructive,
        darkDangerItemHoverColor: tokens.destructive,
        darkDangerItemSelectedBg: errorBg,
        darkDangerItemSelectedColor: tokens.destructive,
        darkGroupTitleColor: tokens.mutedForeground,
        darkItemBg: baseBg,
        darkItemColor: tokens.foreground,
        darkItemDisabledColor: disabledText,
        darkItemHoverBg: hoverBg,
        darkItemHoverColor: tokens.accentForeground,
        darkItemSelectedBg: selectedBg,
        darkItemSelectedColor: tokens.foreground,
        darkPopupBg: elevatedBg,
        darkSubMenuItemBg: baseBg,
        dangerItemActiveBg: errorBg,
        dangerItemColor: tokens.destructive,
        dangerItemHoverColor: tokens.destructive,
        dangerItemSelectedBg: errorBg,
        dangerItemSelectedColor: tokens.destructive,
        groupTitleColor: tokens.mutedForeground,
        horizontalItemBorderRadius: tokens.radius,
        horizontalItemHoverBg: hoverBg,
        horizontalItemHoverColor: tokens.foreground,
        horizontalItemSelectedBg: selectedBg,
        horizontalItemSelectedColor: tokens.foreground,
        itemActiveBg: hoverBg,
        itemBg: baseBg,
        itemBorderRadius: tokens.radius - 2,
        itemColor: tokens.foreground,
        itemDisabledColor: disabledText,
        itemHeight: 38,
        itemHoverBg: hoverBg,
        itemHoverColor: tokens.accentForeground,
        itemMarginBlock: 2,
        itemMarginInline: 4,
        itemPaddingInline: 12,
        itemSelectedBg: selectedBg,
        itemSelectedColor: tokens.foreground,
        popupBg: elevatedBg,
        subMenuItemBg: baseBg,
        subMenuItemBorderRadius: tokens.radius - 2,
        subMenuItemSelectedColor: tokens.foreground,
        zIndexPopup: popupZIndex,
      },
      Message: {
        contentBg: elevatedBg,
        contentPadding: "9px 14px",
        zIndexPopup: 2010,
      },
      Modal: {
        contentBg: elevatedBg,
        footerBg: elevatedBg,
        headerBg: elevatedBg,
        titleColor: tokens.popoverForeground,
        titleFontSize: 16,
        titleLineHeight: 1.5,
      },
      Notification: {
        colorErrorBg: elevatedBg,
        colorInfoBg: elevatedBg,
        colorSuccessBg: elevatedBg,
        colorWarningBg: elevatedBg,
        progressBg: tokens.primary,
        width: 384,
        zIndexPopup: 2050,
      },
      Pagination: {
        itemActiveBg: tokens.primary,
        itemActiveBgDisabled: disabledBg,
        itemActiveColor: tokens.primaryForeground,
        itemActiveColorDisabled: disabledText,
        itemActiveColorHover: tokens.primaryForeground,
        itemBg: baseBg,
        itemInputBg: baseBg,
        itemLinkBg: baseBg,
        itemSize: 34,
        itemSizeLG: 38,
        itemSizeSM: 28,
      },
      Popover: {
        colorBgElevated: elevatedBg,
        colorText: tokens.popoverForeground,
      },
      Popconfirm: {
        zIndexPopup: 1060,
      },
      Progress: {
        circleTextColor: tokens.foreground,
        defaultColor: tokens.primary,
        lineBorderRadius: tokens.radius,
        remainingColor: tokens.muted,
      },
      Radio: {
        buttonBg: baseBg,
        buttonCheckedBg: baseBg,
        buttonCheckedBgDisabled: disabledBg,
        buttonCheckedColorDisabled: disabledText,
        buttonColor: tokens.foreground,
        buttonPaddingInline: 14,
        buttonSolidCheckedActiveBg: tokens.primary,
        buttonSolidCheckedBg: tokens.primary,
        buttonSolidCheckedColor: tokens.primaryForeground,
        buttonSolidCheckedHoverBg: tokens.primary,
        dotColorDisabled: disabledText,
        dotSize: 8,
        radioSize: 16,
      },
      Segmented: {
        itemActiveBg: baseBg,
        itemColor: tokens.mutedForeground,
        itemHoverBg: hoverBg,
        itemHoverColor: tokens.accentForeground,
        itemSelectedBg: baseBg,
        itemSelectedColor: tokens.foreground,
        trackBg: tokens.muted,
      },
      Select: {
        activeBorderColor: tokens.ring,
        activeOutlineColor: alpha(tokens.ring, isDark ? 0.32 : 0.22),
        clearBg: baseBg,
        colorBgElevated: elevatedBg,
        hoverBorderColor: tokens.ring,
        multipleItemBg: tokens.secondary,
        multipleItemBorderColor: tokens.border,
        multipleItemBorderColorDisabled: tokens.border,
        multipleItemColorDisabled: disabledText,
        multipleSelectorBgDisabled: disabledBg,
        optionActiveBg: tokens.accent,
        optionHeight: 34,
        optionPadding: "6px 12px",
        optionSelectedBg: selectedBg,
        optionSelectedColor: tokens.foreground,
        optionSelectedFontWeight: 500,
        selectorBg: baseBg,
        zIndexPopup: popupZIndex,
      },
      Skeleton: {
        blockRadius: tokens.radius,
        gradientFromColor: tokens.muted,
        gradientToColor: isDark ? alpha(tokens.foreground, 0.1) : alpha(tokens.foreground, 0.06),
        paragraphLiHeight: 14,
        paragraphMarginTop: 20,
        titleHeight: 16,
      },
      Slider: {
        dotActiveBorderColor: tokens.primary,
        dotBorderColor: tokens.border,
        handleActiveColor: tokens.primary,
        handleActiveOutlineColor: alpha(tokens.primary, isDark ? 0.28 : 0.18),
        handleColor: tokens.primary,
        handleColorDisabled: disabledText,
        railBg: tokens.muted,
        railHoverBg: tokens.secondary,
        trackBg: tokens.primary,
        trackBgDisabled: disabledBg,
        trackHoverBg: tokens.primary,
      },
      Steps: {
        dotCurrentSize: 10,
        dotSize: 8,
        iconFontSize: 14,
        iconSize: 28,
        iconSizeSM: 24,
        navArrowColor: tokens.mutedForeground,
      },
      Table: {
        borderColor: tokens.border,
        bodySortBg: tokens.muted,
        cellFontSize: 14,
        cellFontSizeMD: 14,
        cellFontSizeSM: 13,
        cellPaddingBlock: 12,
        cellPaddingBlockMD: 10,
        cellPaddingBlockSM: 8,
        cellPaddingInline: 14,
        cellPaddingInlineMD: 12,
        cellPaddingInlineSM: 10,
        expandIconBg: baseBg,
        filterDropdownBg: elevatedBg,
        filterDropdownMenuBg: elevatedBg,
        fixedHeaderSortActiveBg: hoverBg,
        footerBg: baseBg,
        footerColor: tokens.foreground,
        headerBg: tokens.muted,
        headerBorderRadius: tokens.radius,
        headerColor: tokens.mutedForeground,
        headerFilterHoverBg: hoverBg,
        headerSortActiveBg: hoverBg,
        headerSortHoverBg: hoverBg,
        headerSplitColor: tokens.border,
        rowExpandedBg: tokens.muted,
        rowHoverBg: hoverBg,
        rowSelectedBg: selectedBg,
        rowSelectedHoverBg: selectedHoverBg,
        selectionColumnWidth: 40,
        stickyScrollBarBg: alpha(tokens.foreground, isDark ? 0.22 : 0.18),
        stickyScrollBarBorderRadius: tokens.radius,
      },
      Tabs: {
        cardBg: tokens.muted,
        cardGutter: 4,
        cardHeight: 36,
        cardHeightLG: 40,
        cardHeightSM: 32,
        cardPadding: "8px 14px",
        cardPaddingLG: "10px 16px",
        cardPaddingSM: "6px 10px",
        horizontalItemGutter: 24,
        horizontalItemPadding: "10px 0",
        horizontalItemPaddingLG: "12px 0",
        horizontalItemPaddingSM: "8px 0",
        inkBarColor: tokens.primary,
        itemColor: tokens.mutedForeground,
        itemActiveColor: tokens.foreground,
        itemHoverColor: tokens.foreground,
        itemSelectedColor: tokens.foreground,
        titleFontSize: 14,
        titleFontSizeLG: 15,
        titleFontSizeSM: 13,
        zIndexPopup: popupZIndex,
      },
      Tag: {
        defaultBg: tokens.secondary,
        defaultColor: tokens.secondaryForeground,
        solidTextColor: tokens.primaryForeground,
      },
      Tooltip: {
        colorBgSpotlight: tokens.foreground,
        colorTextLightSolid: tokens.background,
      },
      Tree: {
        directoryNodeSelectedBg: tokens.primary,
        directoryNodeSelectedColor: tokens.primaryForeground,
        indentSize: 20,
        nodeHoverBg: hoverBg,
        nodeHoverColor: tokens.accentForeground,
        nodeSelectedBg: selectedBg,
        nodeSelectedColor: tokens.foreground,
        titleHeight: 30,
      },
      TreeSelect: {
        indentSize: 20,
        nodeHoverBg: hoverBg,
        nodeHoverColor: tokens.accentForeground,
        nodeSelectedBg: selectedBg,
        nodeSelectedColor: tokens.foreground,
        titleHeight: 30,
      },
      Typography: {
        titleMarginBottom: 12,
        titleMarginTop: 0,
      },
      Upload: {
        actionsColor: tokens.mutedForeground,
        pictureCardSize: 96,
      },
    },
  };
}
